# fly.toml file generated for toggle on 2021-04-02T16:13:29-04:00

app = "toggle"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "3000"
    restart_limit = 6
    timeout = "2s"
